name: AttentionXML

model:
  hidden_size: 512
  layers_num: 1
  linear_size: [512, 512]
  dropout: 0.5
  emb_trainable: False
  spn_dim: False
  no_grad: False
  without_negative: False

train:
  batch_size: 32
  nb_epoch: 10
  swa_warmup: 2

valid:
  batch_size: 32

predict:
  batch_size: 32

path: models
